### ISSUE TITLE
Invite some people to try it out

### ISSUE THREAD

**Issue by nabsul** [nabsul/kcert#1]
@just1689 As promised, here's the project I've been toying with after giving up on cert-manager.

This is my personal take on what a minimal but useful certificate manager could look like. It installs as a simple service in your cluster, and you manage it via a simple web UI.

Note: You can deploy directly from `nabsul/kcert`, but the more secure thing to do would be building it yourself with the provided docker file. (you really shouldn't run random Docker images in your cluster). 

Also, as a Microsoft employee, I'm very comfortable and productive in .NET, so that's the language it's written in :-)

**Comment by just1689** [comment]
Howdy

Thanks so much for the invite. I've gone over the general approach and I like what you're doing here. 

Looking forward to being involved. I don't really know C# or .NET but I'll do my best.

**Comment by nabsul** [comment]
No worries about knowing the language. Having your feedback early on will be great. I used https://github.com/nabsul/k8s-ecr-login-renew internally for about a year before publishing it and getting useful feedback.

Code contributions are also welcome of course,   but just a warning that I might be doing some major refactoring in these early stages, so it could be a frustrating experience 😃

**Comment by nabsul** [comment]
@chrissound in case this is of interest to you. I'm current using this tool to renew my certs in Digital Ocean K8s.
