### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by coltonfreeman26** [nabsul/kcert#101]
Good day all,
Question about your docker releases. Are the 'sha' releases considered stable or would 1.2.0 be the latest stable release? 
Also, how up to date is the Dockerfile in this repo?

**Comment by nabsul** [comment]
The sha images are only used for testing and could be deleted at any time. 

I didn't understand the dockerfile question though... It's used to build whatever code there is, but doesn't change much itself.

**Comment by coltonfreeman26** [comment]
Good morning,
So then the 1.2.0 is latest? That does answer my question though about the actual Dockerfile. I just noticed that it had not been updated in a while but I suppose that can be typical based off of how it is constructed.

**Comment by nabsul** [comment]
Yes that's the latest version. You can always check it on the releases section of the repo.

The tool is pretty simple, feature complete and there aren't any serious bugs that I'm aware of. Which is why there are few updates 😃

There will be one soon though.

**Comment by coltonfreeman26** [comment]
Awesome, thank you for the info and the quick response. Ill get working on it
