### ISSUE TITLE
Possible to manage hosts with an API instead of modifying the ingress?

### ISSUE THREAD

**Issue by bnssoftware** [nabsul/kcert#104]
From what I can tell, this solution works off changes to Ingress.  We are trying to find a solution that allows us to tell the automated cert solution to add/remove domains directly, without having to modify Ingress.  Is this possible?

**Comment by nabsul** [comment]
Hi, An API doesn't really make sense for KCert because it's a stateless app. It relies on Kubernetes to store its configuration details.

However, you can create certs without creating Ingresses: There's an alternative which is to use configuration objects. There's some information about it here: https://github.com/nabsul/kcert#creating-a-certificate-via-configmap

**Comment by bnssoftware** [comment]
So just to be clear, we're using ingress (ingress-nginx) in front of our service that allows our customers to point their domain to the  external address of the load balancer attached to this ingress.  We then want to generate SSL certs for these domains that come through to the back end service.  Right now, in order for cert-manager to generate the cerrts, we have to specify these domains inside ingress.  We're trying to avoid that part.  Will kcert configmap option work with this?  We still need to use ingress.

**Comment by bnssoftware** [comment]
Ok, this MAY work for us.  I tried the ConfigMap method for test1.mydomain.com with the fake cert and it worked!  However, now when I try to add another one for test2.mydomain.com, I get an error:

$ helm install 1.2.0 nabsul/kcert-configmap -n kcert --debug --set name=kcert,hosts="test2.mydomain.com"        
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: C:\Users\me\AppData\Local\Temp\helm\repository\kcert-configmap-1.0.0.tgz

Error: INSTALLATION FAILED: cannot re-use a name that is still in use
helm.go:84: [debug] cannot re-use a name that is still in use
helm.sh/helm/v3/pkg/action.(*Install).availableName
        helm.sh/helm/v3/pkg/action/install.go:531
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:233
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:306
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:152
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598

**Comment by nabsul** [comment]
replied in other issue  https://github.com/nabsul/kcert/issues/105
