### ISSUE TITLE
Error: INSTALLATION FAILED: cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by bnssoftware** [nabsul/kcert#105]
Using the ConfigMap option to create a certificate, seems to fail when trying to add a second host.

This succeeds: helm install 1.2.0 nabsul/kcert-configmap -n kcert --debug --set name=kcert,hosts="test1.mydomain.com"
This fails: helm install 1.2.0 nabsul/kcert-configmap -n kcert --debug --set name=kcert2,hosts="test2.mydomain.com"

Any idea why?

**Comment by nabsul** [comment]
I think this is a misunderstanding of help and the configmap. You have created a helm deployment named `1.2.0` in the above example, so trying to create a second config map with the same name is giving you this error.

Two solutions:

- Use a different name than `1.2.0` for the second host name.
- Upgrade/Update the existing helm deployment and provide a comma separated list of all your hosts.
