### ISSUE TITLE
Where issued certificate stored after issuing

### ISSUE THREAD

**Issue by kmpartner** [nabsul/kcert#27]
Hi,
After the failure of issuing and renewing certificates with Let's encrypt and cert-manager, I have tried this kcert repository.
Issuing was successful and It seems to be working so far, though I have not yet tested the renewal of certificates after three months.
Thank you for creating,

I have a question about issued certificates. I could confirm the certificate in the browser and I could find created secrets with the same name in ingress using kubectl. 
But I couldn't find certificates using kubectl. 
Where they are stored? Are they in kcert namespace? or are they deleted? 
I am not familiar with issuing certificates and Let's encrypt.

**Comment by nabsul** [comment]
Hi, thanks for trying KCert out.

The Kubernetes secret is where your certs are stored. If you run `kubectl get secrets` the second column called `type` should be `kubernetes.io/tls` for your certificates. 

Please let me know if this answers your question or I misunderstood.

**Comment by kmpartner** [comment]
Thank you for your response,
I now understand where issued certificates are stored.

I am trying to send emails by following the description of this repo.
Sending test email was failed with error messages on the browser page that say development environment show more error ...
How can I enable the environment in the container to see more error?
In container logs, I couldn't find any clue.

Because I couldn't figure out what should I enter in  SMTP__EMAILFROM, SMTP__USER environment variables of deploy.yml, I entered sender email address in both fields. But That may be wrong.

**Comment by nabsul** [comment]
Great!
