### ISSUE TITLE
Support creating certs without Ingresses

### ISSUE THREAD

**Issue by nabsul** [nabsul/kcert#35]
There should be a way to create certs without create Ingresses.

**Comment by rishi-solanki** [comment]
any update on this? I really want to try Kcert even since your podcast. But I didn't because I am waiting for this

**Comment by nabsul** [comment]
I will try to find some time to do this in the next few weeks. I did some experiments and I think I found a reasonable way to do this.

**Comment by nabsul** [comment]
v1.1.0 now has cert creation via ConfigMaps.
