### ISSUE TITLE
Most GET Auth calls return status "invalid"

### ISSUE THREAD

**Issue by ptik31** [nabsul/kcert#55]
Hi,

I have a authentication issue issue with the implementation v1.0.1? (GET Auth)

![image](https://user-images.githubusercontent.com/102354084/178255817-906caa14-b389-4cbf-9193-141432ee5fc9.png)

![image](https://user-images.githubusercontent.com/102354084/178272173-ad37e4b4-0e4d-4975-b9a6-899b284a5e2c.png)

Very rarely a certificate is created (as secret).

Do you know about any issue?

**Comment by ptik31** [comment]
I found out what the problem was -> staging Environment is currently broken ->
[https://community.letsencrypt.org/t/certificates-orders-are-failing-with-500-error/181064/5](url)

On prod it works, but only if I give enough time to the "Ingress propagation". Therefore I would like to create a PR making the propagation time configurable just like the rest of this great solution.

**Comment by nabsul** [comment]
@ptik31 If you're up for it, I suggest exploring if a different solution exists for this. Specifically: I wonder if the nginx ingress controller adds some kind of metadata to the ingress object once it has read and applied the change. If this is the case then the best solution would be:

- Create the ingress
- Watch the ingress object for changes (and periodically check the ingress object)
- Once nginx adds its metadata confirming the change is propagated, continue with the process

If you find such a metadata that can be checked, I'd be happy to help implement it.

**Comment by ptik31** [comment]
In the meanwhile it has been fixed
