### ISSUE TITLE
Typo in chart does not allow to deploy to different namespace

### ISSUE THREAD

**Issue by micw** [nabsul/kcert#73]
In

https://github.com/nabsul/kcert/blob/main/charts/kcert/templates/060-RoleBinding.yaml#L5

Is a copy/paste error that prevents the chart to be deployed on a different namespace than kcert.

Must be `namespace: {{ .Release.Namespace | default "default" }}`

**Comment by nabsul** [comment]
Thanks again for the note.

**Comment by nabsul** [comment]
Fixed in the latest chart release
