### ISSUE TITLE
Condition for acmeKeydoes not work properly with default settings

### ISSUE THREAD

**Issue by micw** [nabsul/kcert#74]
https://github.com/nabsul/kcert/blob/main/charts/kcert/templates/070-Deployment.yaml#L59-L65

The condition `{{- if .Values.acmeKey }}` is true with the provided values.yaml. This results in a section where the secret ref name is NULL which fails to deploy.

Overriding it with `acmeKey=false` in my own values.yaml works as a workaround.

**Comment by nabsul** [comment]
Oh wow, good catch! I wonder why my testing didn't run into this problem... strange. I'll get this fixed in the next few days hopefully.

**Comment by nabsul** [comment]
Fixed in the latest chart release
