### ISSUE TITLE
Is wildcard of subdomain in ingress supported?

### ISSUE THREAD

**Issue by kmpartner** [nabsul/kcert#78]
Thank you for this repository. I have used Kcert for kubernetes deployment.
I will need to create certificates of subdomains using wildcard.

Ingress documentation says that wild card is supported.
https://kubernetes.io/docs/concepts/services-networking/ingress/#hostname-wildcards

I want to use this using Kcert. Is Kcert support wildcard certificate issue?
I just tried but that seems to be failed.

Error
[Error]: Certificate renewal failed.
Error:

Value cannot be null. (Parameter 'uriString')

   at KCert.Services.RenewalHandler.RenewCertAsync(String ns, String secretName, String[] hosts) in /build/Services/RenewalHandler.cs:line 56
   at KCert.Services.KCertClient.RenewCertAsync(Task prev, String ns, String secretName, String[] hosts, CancellationToken tok) in /build/Services/KCertClient.cs:line 84

**Comment by nabsul** [comment]
This is currently not supported. I plan to work on it in January. The prerequisite to that will be: https://github.com/nabsul/kcert/issues/34

**Comment by kmpartner** [comment]
Thank you for reply. I am looking forward to seeing the functionality near future.

**Comment by nabsul** [comment]
Unfortunately I can't commit to adding support for DNS based challenges.
