### ISSUE TITLE
Error checking for cert changes: ingresses.networking.k8s.io is forbidden

### ISSUE THREAD

**Issue by pylaze** [nabsul/kcert#81]
I see this error when installing cert via Helm - 

```
{
  "Timestamp": "2022:12:31 12:35:01.679104",
  "EventId": 0,
  "LogLevel": "Error",
  "Category": "KCert.Services.KCertClient",
  "Message": "HTTP Operation failed with respones: {\u0022kind\u0022:\u0022Status\u0022,\u0022apiVersion\u0022:\u0022v1\u0022,\u0022metadata\u0022:{},\u0022status\u0022:\u0022Failure\u0022,\u0022message\u0022:\u0022ingresses.networking.k8s.io is forbidden: User \\\u0022system:serviceaccount:default:kcert\\\u0022 cannot create resource \\\u0022ingresses\\\u0022 in API group \\\u0022networking.k8s.io\\\u0022 in the namespace \\\u0022kcert\\\u0022\u0022,\u0022reason\u0022:\u0022Forbidden\u0022,\u0022details\u0022:{\u0022group\u0022:\u0022networking.k8s.io\u0022,\u0022kind\u0022:\u0022ingresses\u0022},\u0022code\u0022:403}\n",
  "Exception": "k8s.Autorest.HttpOperationException: Operation returned an invalid status code \u0027Forbidden\u0027\n   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)\n   at k8s.AbstractKubernetes.k8s.INetworkingV1Operations.CreateNamespacedIngressWithHttpMessagesAsync(V1Ingress body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable\u00601 pretty, IReadOnlyDictionary\u00602 customHeaders, CancellationToken cancellationToken)\n   at k8s.NetworkingV1OperationsExtensions.CreateNamespacedIngressAsync(INetworkingV1Operations operations, V1Ingress body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable\u00601 pretty, CancellationToken cancellationToken)\n   at KCert.Services.K8sClient.CreateIngressAsync(V1Ingress ingress) in /build/Services/K8sClient.cs:line 189\n   at KCert.Services.KCertClient.AddChallengeHostsAsync(IEnumerable\u00601 hosts) in /build/Services/KCertClient.cs:line 141\n   at KCert.Services.KCertClient.RenewCertAsync(Task prev, String ns, String secretName, String[] hosts, CancellationToken tok) in /build/Services/KCertClient.cs:line 82",
  "State": {
    "Message": "HTTP Operation failed with respones: {\u0022kind\u0022:\u0022Status\u0022,\u0022apiVersion\u0022:\u0022v1\u0022,\u0022metadata\u0022:{},\u0022status\u0022:\u0022Failure\u0022,\u0022message\u0022:\u0022ingresses.networking.k8s.io is forbidden: User \\\u0022system:serviceaccount:default:kcert\\\u0022 cannot create resource \\\u0022ingresses\\\u0022 in API group \\\u0022networking.k8s.io\\\u0022 in the namespace \\\u0022kcert\\\u0022\u0022,\u0022reason\u0022:\u0022Forbidden\u0022,\u0022details\u0022:{\u0022group\u0022:\u0022networking.k8s.io\u0022,\u0022kind\u0022:\u0022ingresses\u0022},\u0022code\u0022:403}\n",
    "resp": "{\u0022kind\u0022:\u0022Status\u0022,\u0022apiVersion\u0022:\u0022v1\u0022,\u0022metadata\u0022:{},\u0022status\u0022:\u0022Failure\u0022,\u0022message\u0022:\u0022ingresses.networking.k8s.io is forbidden: User \\\u0022system:serviceaccount:default:kcert\\\u0022 cannot create resource \\\u0022ingresses\\\u0022 in API group \\\u0022networking.k8s.io\\\u0022 in the namespace \\\u0022kcert\\\u0022\u0022,\u0022reason\u0022:\u0022Forbidden\u0022,\u0022details\u0022:{\u0022group\u0022:\u0022networking.k8s.io\u0022,\u0022kind\u0022:\u0022ingresses\u0022},\u0022code\u0022:403}\n",
    "{OriginalFormat}": "HTTP Operation failed with respones: {resp}"
  }
}
```

Not sure if this is the cause, but I noticed that the ingress resource did not have a create verbs in the `ClusterRole.yaml` template. I tried creating my own clusterRole with the create value and overriding that in `values.yaml` but that didn't seem to work either

**Comment by nabsul** [comment]
The permission to create this particular ingress should be defined in Role.yaml, not the ClusterRole.

However, what I'm seeing from the logs you've shared is that the service account is in the `default` namespace, while the ingress is being created in the `kcert` namespace. 

The namespace for the service, deployment, role, etc. All appear to be encoded correctly in the chart as `namespace: {{ .Release.Namespace | default "default" }}`..... Aaaand I found the bug:

I forgot to make [this configuration parameter](https://github.com/nabsul/kcert/blob/main/appsettings.json#L14) match the namespace where KCert is being installed.

The fix is easy. If you'd like to try manually, you can edit the KCert deployment and add a new environment variable called `KCERT__NAMESPACE` (with two underscores) and make it equal to `default`.

I can get the chart fixed to reflect this soon.

**Comment by nabsul** [comment]
I'm fairly confident that this is the bug and the update I just published to the Helm chart will fix it. Thanks for reporting this, and please let me know if you have any issues.

**Comment by pylaze** [comment]
Thank you so much for your prompt reply. I will try this shortly and let you know

**Comment by pylaze** [comment]
That seems to have fixed the forbidden error but I seem to be getting a different error now. 
[pod-output.txt](https://github.com/nabsul/kcert/files/10326797/pod-output.txt)

Any advice here? Thanks for your time!

**Comment by nabsul** [comment]
It looks to me like you're using the nginx-ingress-controller. In theory this should work, but I've only tested KCert against ingress-nginx. The names are confusing, but they're not the same thing.

The error you're seeing looks to me like it could be a problem with nginx-ingress-controller, or maybe the ingress definition that KCert creates is missing something that nginx needs.

If you're just getting started with Kubernetes, and don't have a specific reason/need for nginx-ingress-controller, then I'd recommend trying ingress-nginx instead: https://kubernetes.github.io/ingress-nginx/deploy/#quick-start

https://www.nginx.com/blog/guide-to-choosing-ingress-controller-part-4-nginx-ingress-controller-options/

**Comment by pylaze** [comment]
I'm using ingress-nginx 

From my Chart.lock: 
```
- name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.4.2
- name: kcert
  repository: https://nabsul.github.io/helm
  version: 1.0.5
digest: sha256:b8a49c06c56ea3da2b8169b43b25ce373f6e1c40e03f420e08022ac9fc241b7f
generated: "2022-12-30T20:06:17.376134-08:00"
```

**Comment by nabsul** [comment]
Oh, interesting. In that case, I'd recommend researching that webhook error that's in the logs to see if there's any advice for it online. 

This also reminds me that I should probably switch the logging to a more compact format. That JSON is way too much :-)
