### ISSUE TITLE
KCert does not support more than one ingressClass per cluster

### ISSUE THREAD

**Issue by mdgomes** [nabsul/kcert#83]
Hello,

First let me explain my usage of kubernetes, I have a cluster with multiple namespaces each with it's own nginx-ingress (as opposed to a single ingress for the entire cluster). This is a requirement so that I can have multiple hostnames in Azure (each with it's own static IP address).

Example: 
```
kubectl get svc --all-namespaces | grep LoadBalancer
horizontal       horizontal-ingress-nginx-controller                   LoadBalancer   10.0.83.191    51.137.10.234   80:30547/TCP,443:32055/TCP                              53d
productcatalog   productcatalogue-ingress-nginx-controller             LoadBalancer   10.0.127.146   20.82.30.223    80:30584/TCP,443:30684/TCP                              53d
sit              sit-ingress-nginx-controller                          LoadBalancer   10.0.65.221    20.71.66.71     80:31417/TCP,443:30893/TCP                              53d
telco            telco-ingress-nginx-controller                        LoadBalancer   10.0.6.40      104.45.64.105   80:30217/TCP,443:30069/TCP                              53
```

As such each of my Ingresses use a specific ingressClass (for example nginx-productcatalogue, nginx-sit, etc).

The problem is that when KCert detects this ingress it will create an ingress for the .well-known endpoint either using the ChallengeIngress.ClassName or ChallengeIngress.Annotations.kubernetes.io/ingress.class value (depending on the configuration).

This is problematic because, currently the only way to refresh certificates is manually setting the above variables to match the correct ingress class name so that the correct nginx exposes the .well-known endpoint in the correct host/IP.

In my opinion KCert should generate the .well-known ingresses using the value of the ingressClass of each managed ingress. This can be an option obviously to extend existing options.

**Comment by nabsul** [comment]
Hi @mdgomes , That's a very interesting scenario that I didn't consider.

Probably the simplest way to support this is to recommend running multiple instances of KCert, one for each namespace, and configure each instance of KCert with the different ingress classnames / annotations. I haven't tested this scenario though, and there may be some hard-coded bits in KCert that need to be parameterize to make this work.

Your suggestion to just follow the annotation/classname of the ingress sounds like it could work. I'll just need to think about it a bit more to make sure it doesn't break anything. 

I can't promise you when I'll get around to looking at this, but this is interesting to me, and I would like to solve this problem. But I expect it will be difficult for me to make any progress on this until February.

**Comment by mdgomes** [comment]
Hello  @nabsul, thank you for the feedback.

I can confirm that setting up kcert per namespace works. Although it has to be done manually because the serviceaccount,clusterrole and clusterrolebinding will clash if using helm to install (maybe add an if to the helm chart to skip creation of the non namespace scoped stuff?). It will obviously produce multiple ingresses from the different namespaces.

Additionally, if this is to be a recommended option I would suggest adding something like nginx's --scan-namespace to limit the scope to ingresses of a given namespace (nginx only scans all namespaces if the ingressClass is nginx or empty for example).

**Comment by nabsul** [comment]
Hey @mdgomes ! I started to work on a change to the Helm chart so that clusterrole creation was optional, but then I realized: You just need to rename the clusterrole and clusterrole binding to avoid the conflict.

I think that approach is better than making the different helm installation share a common cluster role. The chart values are here: https://github.com/nabsul/kcert/blob/main/charts/kcert/values.yaml#L21
