### ISSUE TITLE
Error from server (BadRequest): container “kcert” in pod “kcert-XXXXXX” is waiting to start: trying and failing

### ISSUE THREAD

**Issue by Stav352** [nabsul/kcert#87]
There's an issue with the kcertImage version value - it is set to 1.2.0 while there is none in the docker repository. 
(It needs to be set to 'latest' for now, I assume)

**Comment by nabsul** [comment]
It seems like it exists: https://hub.docker.com/layers/nabsul/kcert/v1.2.0/images/sha256-3aa8bd88db4968e7a8544862b2043f373ec6df98bc960e40984700b1d3af7fce?context=explore
