### ISSUE TITLE
Support for non-nginx ingress controllers

### ISSUE THREAD

**Issue by ruckc** [nabsul/kcert#91]
I have a kubernetes cluster with traefik as the ingress controller.

When I create an ingress with label `kcert.dev/ingress: managed` and `ingressClassName: traefik`, the kcert created ingress for the acme-challenge is hardocded to `ingressClassName: nginx`.  I believe this is hardcoded from appsettings.json, and I'm not sure how to override that via the helm chart, or if it's possible to override that.

It would be beneficial if you picked up the `ingressClassName` from the source ingress, or let us specify the desired `ingressClassName` in helm values.

**Comment by nabsul** [comment]
#86

**Comment by nabsul** [comment]
The latest chart allows to add env vars to the deployment. You should be able to set to modify this value now.
