### ISSUE TITLE
Ability to constraint to a single namespace

### ISSUE THREAD

**Issue by Zegorax** [nabsul/kcert#99]
Hello,

Would it be possible to add a configuration to constraint all K8S API requests to a predefined namespace ?

In our environment, we have only access to a single namespace, therefore calling ListSecretForAllNamespaces is failing since the API will deny the cluster-wide request.

**Comment by nabsul** [comment]
That should be quite doable (and is a great idea). I'm planning to catch up on requests and soon and cut a new release, so hopefully it won't be too long before I can add this.

**Comment by nabsul** [comment]
included in #100
